# Generated by Django 2.0.9 on 2025-02-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('totalpage', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bookborrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('returned_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.book')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('message_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='communitymembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMUNITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.community')),
            ],
        ),
        migrations.CreateModel(
            name='communitypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('COMMUNITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.community')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('extra_days', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('BOOK_BORROW', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.bookborrow')),
            ],
        ),
        migrations.CreateModel(
            name='friend_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('req_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='library_membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('LIBRARIAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.librarian')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('registerno', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.login')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='like',
            name='POST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='library_membership',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='librarian',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.login'),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='communitymembers',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='community',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='POST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='chat',
            name='FRIEND',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.friend_request'),
        ),
        migrations.AddField(
            model_name='chat',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.login'),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.student'),
        ),
        migrations.AddField(
            model_name='book',
            name='LIBRARIAN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.librarian'),
        ),
    ]
