# Generated by Django 2.0.9 on 2025-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegemediaAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='image',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
