# Generated by Django 2.0.9 on 2025-03-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollegemediaAPP', '0002_librarian_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('chat', models.CharField(max_length=200)),
                ('COMMUNITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.community')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegemediaAPP.login')),
            ],
        ),
    ]
